# Generated by Django 2.1.1 on 2018-09-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NowLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('admin_area', models.CharField(max_length=20)),
                ('cnty', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp', models.IntegerField()),
                ('hum', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('wind_sc', models.IntegerField()),
                ('cond_code', models.IntegerField()),
                ('cond_txt', models.CharField(max_length=10)),
                ('aqi', models.IntegerField()),
                ('qlty', models.CharField(max_length=10)),
                ('pm_10', models.IntegerField()),
                ('pm_25', models.IntegerField()),
                ('no_2', models.IntegerField()),
                ('so_2', models.IntegerField()),
                ('co', models.IntegerField()),
                ('dsg', models.CharField(max_length=50)),
                ('flu', models.CharField(max_length=50)),
                ('sports', models.CharField(max_length=50)),
                ('air', models.CharField(max_length=50)),
                ('now_city', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='fog_detect.NowLoc')),
            ],
        ),
    ]
